### ISSUE TITLE
Empty outfile issue 

### ISSUE THREAD

**Issue by ahmadkhalaf1** [fatso83/grunt-penthouse#21] opened 2017-01-08 11:06 UTC
Hello , 
after running the code console " done without erros" then the outfile css is empty 

 penthouse: {
      options: {
        outfile: 'assets/css/test.css',
        css: 'assets/css/main.css',
        url: 'html/ss/ss.html',
        width : 420,
        height : 480,
        skipErrors : false // this is the default
      },
  },
this is the code and its empry inside text.css

**Comment by fatso83** [comment] 2017-01-08 23:34
well, the setup seems fine, so it must be something to do with the code. can you post any code at all? remember, penthouse will check what css is active "above the fold", so there of course needs to be some css that is active ... 

My guess is that this is a penthouse issue, not this tiny plugin, in which case I would consult the [issue tracker for Penthouse](https://github.com/pocketjoso/penthouse/issues).

First, do the simple thing and [check with the online version of Penthouse](https://jonassebastianohlsson.com/criticalpathcssgenerator/). If this works then there is probably something wrong with this grunt module, but if it does not give you any results I would ask on the issue tracker for Penthouse, as then it seems that either Penthouse is screwing up or you are 😄

**Comment by fatso83** [comment] 2017-01-12 15:52
Closing due to not enough information. Unable to reproduce without more data.

**Closed by fatso83** 2017-01-12 15:52 UTC
