### ISSUE TITLE
grunt penthouse triggers infinite loop

### ISSUE THREAD

**Issue by vchouhan** [fatso83/grunt-penthouse#11] opened 2015-08-06 21:20 UTC
```javascript
grunt.initConfig({
        penthouse: {
            extract: {
                outfile: 'build/css/critical.css',
                css: 'build/css/spa.min.css',
                url: 'http://localhost/~vc/voSpa/build/spa.html',
                width: 1300,
                height: 900
            },
        }
});
```
Registered Task
grunt.registerTask('phBuild', ['penthouse:extract']);

Console status when I run grunt penthouse -v
Running tasks: penthouse

Running "penthouse" task

Running "penthouse" task

Running "penthouse" task

Running "penthouse" task

Running "penthouse" task

**Comment by pocketjoso** [comment] 2015-08-07 07:32
With a setup as similar to yours as I can reproduce, running both `grunt phBuild` and `grunt penthouse -v` yields expected results...

@fatso83 any ideas?

**Comment by pocketjoso** [comment] 2015-08-07 07:36
@vchouhan If you could post your full `Gruntfile`, that would help.

**Comment by fatso83** [comment] 2015-08-07 07:55
Yeah,  disclose the full setup. I think something is hiding the actual reason. On vacation with only mobile, so back from the 17th, if this needs debugging.

**Comment by dougfelton** [comment] 2015-10-21 18:54
Two thoughts since this is still open:

1) I just had this happen to me as well, but when I renamed my task from 'penthouse' to 'headcss', it started working as expected.

2) I'm guessing the real problem is that your task is named 'phBuild', but you say that you're running  'grunt penthouse -v' on the command line.  What happens when you run 'grunt phBuild -v' instead?

Here are the two pertinent parts of my work Gruntfile:

```javascript
penthouse: {
    dev: {
        outfile: 'web/dist_dev/css/criticalcss-site-index.css',
        css: 'web/dist_dev/css/styles.css',
        url: 'http://localhost',
        width: 1300,
        height: 900
    }
},
```

and

```javascript
grunt.registerTask('headcss', ['penthouse:dev']);
```

**Comment by fatso83** [comment] 2015-11-19 18:25
@dougfelton : no wonder you got a loop, as your task definition was recursive :smile_cat: 

Closing this as I cannot see any errors actually relating to the plugin.

**Closed by fatso83** 2015-11-19 18:25 UTC
